import type { NextPage } from "next";
import Head from "next/head";
import Link from 'next/link'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Venlo NextJS App</title>
        <meta name="description" content="Generated by venlo" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Venlo NextJS App</div>
    </>
  );
};

export default Home;
