name: Release
permissions:
  contents: write
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3.7.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-count: "0"

      - name: Print the changelog
        run: echo "${{ steps.changelog.outputs.tag }}"

      - name: Print the changelog
        run: echo "${{ steps.changelog.outputs.version }}"

      - name: Print the changelog
        run: echo "${{ steps.changelog.outputs.clean_changelog }}" > notes.text

      - name: Create Release
        run: gh release create ${{ steps.changelog.outputs.tag  }} --notes-file notes.text
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: make a gitconfig
        run: |
          echo -e "[user]
            name = github-runner
            email = githubrunner@io37.ch
          " > ~/.gitconfig

      - name: is gitconfig there
        run: cat ~/.gitconfig

      - name: installs the site
        run: npm_config_yes=true npx venlo@latest --default site documentation

      - name: empties template pages
        run: rm -rf site/src/pages/[a-z]*.astro

      - name: copies top level mds
        run: for f in *.md; do cp "$f" "site/src/content/top/$(echo "$f" | tr '[:upper:]' '[:lower:]' )"; done

      - name: copies top readme to index
        run: cp README.md site/src/content/top/index.md

      - name: Build
        run: cd site && make build

      - name: Rsync
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -a
          path: site/dist/
          remote_path: "/var/www/html/venlo.io37.ch"
          remote_host: venlo.io37.ch
          remote_user: deploy
          remote_key: ${{ secrets.DEPLOY_KEY }}
