name: Publish to NPM
on:
  push:
    branches: [ action ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
            
      - name: Install JS Packages
        run: npm publish