name: Test
on:
  push:
    branches-ignore:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      STAGING_URL: asda.io37.ch

    steps:
      - uses: actions/checkout@v3
      - name: make a gitconfig
        run: |
          echo -e "[user]
            name = github-runner
            email = githubrunner@io37.ch
          " > ~/.gitconfig

      - name: is gitconfig there
        run: cat ~/.gitconfig

      - name: install packages
        run: npm i

      - name: installs the site
        run: node bin/init.js --astro venlo readme

      - name: copies top level mds
        run: for f in *.md; do cp "$f" "venlo/src/content/top/$(echo "$f" | tr '[:upper:]' '[:lower:]')"; done

      - name: copies top readme to index
        run: cp README.md venlo/src/content/top/index.md

      - name: Build
        run: cd venlo && make build

      - name: Create branch.html
        run: |
          cp .github/templates/branch.html dist/branch.html
          cp .github/templates/workflow.css dist/workflow.css
          sed -i 's|\[REPO_NAME\]|'"$GITHUB_REPOSITORY"'|g' dist/branch.html
          sed -i 's|\[BRANCH_NAME\]|'"$(echo $GITHUB_REF | sed 's|refs/heads/||')"'|g' dist/branch.html
          sed -i 's|\[DATE\]|'"$(date)"'|g' dist/branch.html

      - name: Rsync
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -a
          path: dist/
          remote_path: "/var/www/html/$STAGING_URL"
          remote_host: $STAGING_URL
          remote_user: deploy
          remote_key: ${{ secrets.DEPLOY_KEY }}
